CREATE TABLE game_type (
  id int IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(45) NULL,
  description VARCHAR(200) NULL,
  insert_date DATETIME DEFAULT GETDATE());

CREATE TABLE player (
  id int IDENTITY(1,1) PRIMARY KEY,
  email VARCHAR(45) NULL,
  insert_date DATETIME DEFAULT GETDATE());